from enum import IntEnum


class GTSRBLabelEnum(IntEnum):
    @classmethod
    def _missing_(cls, key):
        return cls.UNKNOWN

    MAX_SPEED_20 = 0
    MAX_SPEED_30 = 1
    MAX_SPEED_50 = 2
    MAX_SPEED_60 = 3
    MAX_SPEED_70 = 4
    MAX_SPEED_80 = 5
    NO_MAX_SPEED_80 = 6
    MAX_SPEED_100 = 7
    MAX_SPEED_120 = 8
    NO_OVERTAKING = 9
    NO_OVERTAKING_FOR_TRUCKS = 10
    PRIORITY_IN_TRAFFIC_NEXT_CROSSING = 11
    PRIORITY_IN_TRAFFIC_ROAD = 12
    YIELD = 13
    STOP = 14
    NO_VEHICLES_PERMITTED_CIRCLE = 15
    TRUCK_DRIVING_LEFT = 16
    NO_VEHICLES_PERMITTED_WHITE_BOX = 17
    WARNING = 18
    DANGEROUS_CURVE_TO_LEFT = 19
    DANGEROUS_CURVE_TO_RIGHT = 20
    DANGEROUS_DOUBLE_CURVE = 21
    BUMPY_ROAD = 22
    SLIPPERY_ROAD = 23
    ROAD_NARROWS_FROM_RIGHT = 24
    CONSTRUCTION_SITE = 25
    TRAFFIC_LIGHT_AHEAD = 26
    PEDESTRIAN = 27
    CHILDREN_CROSSING = 28
    BICYCLE_AHEAD = 29
    SNOWY_ROAD = 30
    DEER_CROSSING = 31
    NO_MAX_SPEED = 32
    TURN_RIGHT = 33
    TURN_LEFT = 34
    GO_STRAIGHT = 35
    GO_STRAIGHT_OR_RIGHT = 36
    GO_STRAIGHT_OR_LEFT = 37
    DRIVE_RIGHT = 38
    DRIVE_LEFT = 39
    ROUNDABOUT = 40
    PASSING_ALLOWED = 41
    PASSING_ALLOWED_FOR_TRUCKS = 42
    UNKNOWN = -1
